# Generated by Django 4.0.3 on 2022-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.BigIntegerField(),
        ),
    ]
