# Generated by Django 4.0.3 on 2022-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_bill_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.IntegerField(max_length=100),
        ),
    ]
